#NOTE: ignore some of the special processing included palantir subscription (e.g. https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/Authentication.xml#L48)
winlogbeat.event_logs:
  #account lockout: https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/Account-Lockout.xml
  - name: Security
    event_id: 4740
    level: info
    provider:
      - Microsoft-Windows-Security-Auditing

  #account management: https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/Account-Management.xml
  - name: Security
    event_id: 4627, 4703, 4704, 4705, 4720, 4737-4739, 4780-4782, 4793, 4794, 4798, 4799, 5376, 5377
  - name: Security
    event_id: 4722-4735
  - name: Security
    event_id: 4741-4753
  - name: Security
    event_id: 4754-4767

  #active directory: https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/Active-Directory.xml
  - name: Security
    event_id: 4662, 14080, 5136, 5137, 5178, 5139, 5141, 4713, 4706, 4707, 4716, 4717, 4718, 4739, 4864, 4865, 4866, 4867

  #application crashes: https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/Application-Crashes.xml
  - name: Application
    event_id: 1000, 1002
    level: error
    provider:
      - Application Error
      - Application Hang
  - name: Application
    event_id: 1001
    level: info
    provider:
      - Windows Error Reporting

  #applocker: https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/Applocker.xml
  - name: Microsoft-Windows-AppLocker/EXE and DLL
  - name: Microsoft-Windows-AppLocker/MSI and Script
  - name: Microsoft-Windows-AppLocker/Packaged app-Execution
  - name: Microsoft-Windows-AppLocker/Packaged app-Deployment

  #authentication: https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/Authentication.xml
  - name: Security
    event_id: 4624-4626, 4634, 4647, 4649, 4672, 4675, 4774-4779, 4800-4803, 4964, 5378

  #autoruns: https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/Autoruns.xml
  #make sure to set up the scheduled autoruns service
  - name: Autoruns

  #bits: https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/Bits-Client.xml
  - name: Microsoft-Windows-Bits-Client/Operational

  #certificate authority: https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/Certificate-Authority.xml
  - name: Security
    event_id: 4886, 4887, 4888

  #code integrity: https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/Code-Integrity.xml
  - name: Microsoft-Windows-CodeIntegrity/Operational
    event_id: 3001, 3002, 3003, 3004, 3010, 3023
    level: error, warning
    provider:
      - Microsoft-Windows-CodeIntegrity
  - name: Security
    event_id: 5038, 6281, 6410
    level: info
    provider:
      - Microsoft-Windows-Security-Auditing

  #dns: https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/DNS.xml
  - name: Microsoft-Windows-DNS-Client/Operational
    event_id: 3008
  - name: DNS Server
    event_id: 150, 770
  - name: Microsoft-Windows-DNSServer/Audit
    event_id: 541

  #device guard: https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/Device-Guard.xml
  - name: Microsoft-Windows-DeviceGuard/Operational

  #drivers: https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/Drivers.xml
  - name: System
    event_id: 219
    level: warning
    provider: 
      - Microsoft-Windows-Kernel-PnP
  - name: Microsoft-Windows-DriverFrameworks-UserMode/Operational
    event_id: 2004

  #emet: https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/EMET.xml
  - name: Application
    event_id: 1, 2
    level: warning, error
    provider:
      - EMET

  #event log diagnostics: https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/Event-Log-Diagnostics.xml
  - name: System
    provider:
      - Microsoft-Windows-Eventlog
  - name: Security
    event_id: 1100, 1104, 1105, 1108

  #explicit credentials: https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/Explicit-Credentials.xml
  - name: Security
    level: info
    provider: 
      - Microsoft-Windows-Security-Auditing

  #exploit guard: https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/Exploit-Guard.xml
  - name: Microsoft-Windows-Windows Defender/Operational
    event_id: 1121, 1122, 5007
  - name: Microsoft-Windows-Windows Defender/WHC
    event_id: 1121, 1122, 5007
  - name: Microsoft-Windows-Windows Defender/Operational
    event_id: 1123, 1124, 5007
  - name: Microsoft-Windows-Windows Defender/WHC
    event_id: 1123, 1124, 5007
    #need to split these? https://www.elastic.co/guide/en/beats/winlogbeat/current/configuration-winlogbeat-options.html
  - name: Microsoft-Windows-Security-Mitigations/KernelMode
    event_id: 1-12, 5, 260
    provider: 
      - Microsoft-Windows-Security-Mitigations
      - Microsoft-Windows-WER-Diag
      - Microsoft-Windows-Win32kv
      - Win32k
  - name: Microsoft-Windows-Security-Mitigations/KernelMode
    event_id: 12-24
    provider: 
      - Microsoft-Windows-Security-Mitigations
      - Microsoft-Windows-WER-Diag
      - Microsoft-Windows-Win32kv
      - Win32k
  - name: Microsoft-Windows-Win32k/Concurrency
    event_id: 1-12, 5, 260
    provider: 
      - Microsoft-Windows-Security-Mitigations
      - Microsoft-Windows-WER-Diag
      - Microsoft-Windows-Win32kv
      - Win32k
  - name: Microsoft-Windows-Win32k/Concurrency
    event_id: 12-24
    provider: 
      - Microsoft-Windows-Security-Mitigations
      - Microsoft-Windows-WER-Diag
      - Microsoft-Windows-Win32kv
      - Win32k
  - name: Microsoft-Windows-Win32k/Contention
    event_id: 1-12, 5, 260
    provider: 
      - Microsoft-Windows-Security-Mitigations
      - Microsoft-Windows-WER-Diag
      - Microsoft-Windows-Win32kv
      - Win32k
  - name: Microsoft-Windows-Win32k/Contention
    event_id: 12-24
    provider: 
      - Microsoft-Windows-Security-Mitigations
      - Microsoft-Windows-WER-Diag
      - Microsoft-Windows-Win32kv
      - Win32k
  - name: Microsoft-Windows-Win32k/Messages
    event_id: 1-12, 5, 260
    provider: 
      - Microsoft-Windows-Security-Mitigations
      - Microsoft-Windows-WER-Diag
      - Microsoft-Windows-Win32kv
      - Win32k
  - name: Microsoft-Windows-Win32k/Messages
    event_id: 12-24
    provider: 
      - Microsoft-Windows-Security-Mitigations
      - Microsoft-Windows-WER-Diag
      - Microsoft-Windows-Win32kv
      - Win32k
  - name: Microsoft-Windows-Win32k/Operational
    event_id: 1-12, 5, 260
    provider: 
      - Microsoft-Windows-Security-Mitigations
      - Microsoft-Windows-WER-Diag
      - Microsoft-Windows-Win32kv
      - Win32k
  - name: Microsoft-Windows-Win32k/Operational
    event_id: 12-24
    provider: 
      - Microsoft-Windows-Security-Mitigations
      - Microsoft-Windows-WER-Diag
      - Microsoft-Windows-Win32kv
      - Win32k
  - name: Microsoft-Windows-Win32k/Power
    event_id: 1-12, 5, 260
    provider: 
      - Microsoft-Windows-Security-Mitigations
      - Microsoft-Windows-WER-Diag
      - Microsoft-Windows-Win32kv
      - Win32k
  - name: Microsoft-Windows-Win32k/Power
    event_id: 12-24
    provider: 
      - Microsoft-Windows-Security-Mitigations
      - Microsoft-Windows-WER-Diag
      - Microsoft-Windows-Win32kv
      - Win32k
  - name: Microsoft-Windows-Win32k/Render
    event_id: 1-12, 5, 260
    provider: 
      - Microsoft-Windows-Security-Mitigations
      - Microsoft-Windows-WER-Diag
      - Microsoft-Windows-Win32kv
      - Win32k
  - name: Microsoft-Windows-Win32k/Render
    event_id: 12-24
    provider: 
      - Microsoft-Windows-Security-Mitigations
      - Microsoft-Windows-WER-Diag
      - Microsoft-Windows-Win32kv
      - Win32k
  - name: Microsoft-Windows-Win32k/Tracing
    event_id: 1-12, 5, 260
    provider: 
      - Microsoft-Windows-Security-Mitigations
      - Microsoft-Windows-WER-Diag
      - Microsoft-Windows-Win32kv
      - Win32k
  - name: Microsoft-Windows-Win32k/Tracing
    event_id: 12-24
    provider: 
      - Microsoft-Windows-Security-Mitigations
      - Microsoft-Windows-WER-Diag
      - Microsoft-Windows-Win32kv
      - Win32k
  - name: Microsoft-Windows-Win32k/UIPI
    event_id: 1-12, 5, 260
    provider: 
      - Microsoft-Windows-Security-Mitigations
      - Microsoft-Windows-WER-Diag
      - Microsoft-Windows-Win32kv
      - Win32k
  - name: Microsoft-Windows-Win32k/UIPI
    event_id: 12-24
    provider: 
      - Microsoft-Windows-Security-Mitigations
      - Microsoft-Windows-WER-Diag
      - Microsoft-Windows-Win32kv
      - Win32k
  - name: System
    event_id: 1-12, 5, 260
    provider:
      - Microsoft-Windows-Security-Mitigations
      - Microsoft-Windows-WER-Diag
      - Microsoft-Windows-Win32kv
      - Win32k
  - name: System
    event_id: 12-24
    provider:
      - Microsoft-Windows-Security-Mitigations
      - Microsoft-Windows-WER-Diag
      - Microsoft-Windows-Win32kv
      - Win32k 
  - name: Microsoft-Windows-Security-Mitigations/UserMode
    event_id: 1-12, 5, 260
    provider: 
      - Microsoft-Windows-Security-Mitigations
      - Microsoft-Windows-WER-Diag
      - Microsoft-Windows-Win32kv
      - Win32k
  - name: Microsoft-Windows-Security-Mitigations/UserMode
    event_id: 12-24
    provider: 
      - Microsoft-Windows-Security-Mitigations
      - Microsoft-Windows-WER-Diag
      - Microsoft-Windows-Win32kv
      - Win32k
  - name: Microsoft-Windows-Windows Defender/Operational
    event_id: 1125, 1126, 5007
  - name: Microsoft-Windows-Windows Defender/WHC
    event_id: 1125, 1126, 5007

  #external devices: https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/External-Devices.xml
  - name: Microsoft-Windows-Kernel-PnP/Configuration
    event_id: 400, 410
    level: info
    provider: 
      - Microsoft-Windows-Kernel-PnP
  - name: Security
    event_id: 6416
  - name: Security
    event_id: 6419-6424

  #firewall: https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/Firewall.xml
  - name: Microsoft-Windows-Windows Firewall With Advanced Security/Firewall
    event_id: 2004, 2005, 2006, 2033
    level: info, error
    provider:
      - Microsoft-Windows-Windows Firewall With Advanced Security
  - name: Security
    event_id: 4944-4954
  - name: Security
    event_id: 4956-4958
  - name: Security
    event_id: 5024, 5025, 5037
  - name: Security
    event_id: 5027-5030
  - name: Security
    event_id: 5032-5035

  #gpo errors: https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/Group-Policy-Errors.xml
  - name: System
    event_id: 1085, 1125, 1127, 1129
    level: error
    provider:
      - Microsoft-Windows-GroupPolicy
  - name: Security
    event_id: 6144, 6145

  #kerberos: https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/Kerberos.xml
  - name: Security
    event_id: 4768, 4769, 4770, 4771, 4772, 4773

  #log deletion security: https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/Log-Deletion-Security.xml
  - name: Security
    event_id: 1102
    level: info
    provider:
      - Microsoft-Windows-Eventlog

  #log deletion system: https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/Log-Deletion-System.xml
  - name: System
    event_id: 104
    level: info
    provider:
      - Microsoft-Windows-Eventlog

  #msi: https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/MSI-Packages.xml
  - name: Application
    event_id: 1022, 1033
    provider:
      - MsiInstaller
  - name: Setup
    event_id: 2, 0
    provider:
      - Microsoft-Windows-Servicing
  - name: Microsoft-Windows-Application-Experience/Program-Inventory
    event_id: 903, 904
    provider:
      - Microsoft-Windows-Application-Experience
  - name: Microsoft-Windows-Application-Experience/Program-Inventory
    event_id: 905, 906
    provider:
      - Microsoft-Windows-Application-Experience
  - name: Microsoft-Windows-Application-Experience/Program-Inventory
    event_id: 907, 908
    provider:
      - Microsoft-Windows-Application-Experience
  - name: Microsoft-Windows-Application-Experience/Program-Inventory
    event_id: 800
    provider:
      - Microsoft-Windows-Application-Experience
  
  #office: https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/Microsoft-Office.xml
  - name: OAlerts

  #ntml: https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/NTLM.xml
  - name: Microsoft-Windows-Authentication/AuthenticationPolicyFailures-DomainController
    provider:
      - Microsoft-Windows-NTLM
  - name: Microsoft-Windows-Authentication/ProtectedUserFailures-DomainController
    provider:
      - Microsoft-Windows-NTLM
  - name: Microsoft-Windows-NTLM/Operational
    provider:
      - Microsoft-Windows-NTLM

  #object manipulation: https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/Object-Manipulation.xml
  - name: Security
    event_id: 4715, 4817, 4656, 4658, 4660, 4663, 4670

  #operating system: https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/Operating-System.xml
  - name: System
    event_id: 12, 13
    provider:
      - Microsoft-Windows-Kernel-General
  - name: Security
    event_id: 4608
  - name: System
    event_id: 1074
    provider:
      - USER32
  - name: Security
    event_id: 4817, 4826
  - name: System
    event_id: 16962, 16965, 16968, 16969
  - name: Microsoft-Windows-SMBServer/Audit
    event_id: 3000
    provider:
      - Microsoft-Windows-SMBServer
  - name: System
    event_id: 41, 1001, 6008, 4621
  - name: Security
    event_id: 4610, 4611, 4614, 4622, 4697
  - name: Security
    event_id: 4719, 4817, 4902, 4906, 4908, 4912, 4904, 4905

  #powershell: https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/Powershell.xml
  - name: Microsoft-Windows-PowerShell/Operational
  - name: Microsoft-Windows-PowerShell-DesiredStateConfiguration-FileDownloadManager/Operational
  - name: Windows PowerShell

  #print: https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/Print.xml
  - name: Microsoft-Windows-PrintService/Operational
    event_id: 307
    level: info
    provider: 
      - Microsoft-Windows-PrintService

  #privilege use: https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/Privilege-Use.xml
  - name: Security
    event_id: 4673, 4674, 4985

  #process exec: https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/Process-Execution.xml
  - name: Security
    event_id: 4688
  - name: Security
    event_id: 4689

  #registry: https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/Registry.xml
  #TODO: how to filter on eventdata operationtype?
  - name: Security
    event_id: 4657
  
  #services: https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/Services.xml
  - name: System
    event_id: 7022, 7023, 7024, 7026, 7031, 7032, 7034
    level: info, critical, error, warning
    provider:
      - Service Control Manager
  - name: System
    event_id: 7045, 7040
    level: info, critical, error, warning
    provider:
      - Service Control Manager

  #shares: https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/Shares.xml
  - name: Security
    event_id: 5140, 5142, 5144, 5145, 5168
  - name: Microsoft-Windows-SMBClient/Operational
    event_id: 30622, 30624
  - name: Microsoft-Windows-SMBClient/Security
  - name: Microsoft-Windows-SMBServer/Security

  #smart card: https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/Smart-Card.xml
  - name: Microsoft-Windows-SmartCard-Audit/Authentication

  #software restrictions: https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/Software-Restriction-Policies.xml
  - name: Application
    event_id: 865, 866, 867, 868, 882
    provider: 
      - Microsoft-Windows-SoftwareRestrictionPolicies

  #sysmon: https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/Sysmon.xml
  - name: Microsoft-Windows-Sysmon/Operational

  #system time change: https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/System-Time-Change.xml
  - name: Security
    event_id: 4616

  #task scheduler: https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/Task-Scheduler.xml
  - name: Microsoft-Windows-TaskScheduler/Operational
    event_id: 106, 129, 141, 142, 200, 201
    provider: 
      - Microsoft-Windows-TaskScheduler
  - name: Security
    event_id: 4698-4702

  #terminal services: https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/Terminal-Services.xml
  - name: Microsoft-Windows-TerminalServices-Gateway/Admin
  - name: Microsoft-Windows-TerminalServices-Gateway/Operational
  - name: Microsoft-Windows-TerminalServices-ClientUSBDevices/Admin
  - name: Microsoft-Windows-TerminalServices-ClientUSBDevices/Operational
  - name: Microsoft-Windows-TerminalServices-PnPDevices/Admin
  - name: Microsoft-Windows-TerminalServices-PnPDevices/Operational
  - name: Microsoft-Windows-TerminalServices-Printers/Admin
  - name: Microsoft-Windows-TerminalServices-Printers/Operational
  - name: Microsoft-Windows-TerminalServices-ServerUSBDevices/Admin
  - name: Microsoft-Windows-TerminalServices-ServerUSBDevices/
  
  #wmi: https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/WMI.xml
  - name: Microsoft-Windows-WMI-Activity/Operational
  - name: Microsoft-Windows-TPM-WMI

  #windows defender: https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/Windows-Defender.xml
  - name: Microsoft-Windows-Windows Defender/Operational
    event_id: 1006-1009
  - name: Microsoft-Windows-Windows Defender/Operational
    event_id: 1116-1119
  
  #windows update: https://github.com/palantir/windows-event-forwarding/blob/master/wef-subscriptions/Windows-Updates.xml
  - name: Microsoft-Windows-WindowsUpdateClient/Operational
    event_id: 19, 20, 24, 25, 31, 34, 35
    level: error
    provider:
      - Microsoft-Windows-WindowsUpdateClient
  - name: Setup
    event_id: 1009
    level: info
    provider:
      - Microsoft-Windows-Servicing

output.logstash:
  hosts: ["10.0.0.1:5044"]

logging.to_files: true
logging.files:
  path: C:/ProgramData/winlogbeat/Logs
logging.level: info